# Generated by Django 5.2.7 on 2025-10-28 18:40

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Порода')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес (кг)')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мальчик'), ('F', 'Девочка')], max_length=1, null=True, verbose_name='Пол')),
                ('features', models.TextField(blank=True, help_text='Аллергии, хронические заболевания и другие особенности питомца', null=True, verbose_name='Особенности')),
                ('owners', models.ManyToManyField(related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
