# Generated by Django 5.2.7 on 2025-10-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='custom_pet_type',
            field=models.CharField(blank=True, help_text='Укажите, если выбрали "Другое"', max_length=100, null=True, verbose_name='Свой вариант'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('dog', '🐶 Собака'), ('cat', '🐱 Кошка'), ('bird', '🐦 Птица'), ('rodent', '🐹 Грызун'), ('rabbit', '🐰 Кролик'), ('reptile', '🐍 Рептилия'), ('fish', '🐠 Рыбка'), ('other', '❓ Другое (указать)')], default='dog', max_length=20, verbose_name='Тип животного'),
        ),
    ]
